### ISSUE TITLE
Add log path to job model

### ISSUE THREAD

**Issue by nikhil** [mskcc/ridgeback#176]

**Comment by sivkovic** [comment]
I think that better approach would be to use some monitoring software such as ELK, and store logs there.

**Comment by nikhil** [comment]
I think that is fine, but we should not keep in our head that the log is called "lsf.log" maybe it should go in some documentation or something,

**Comment by allanbolipata** [comment]
Since we plan on handling this with ELK, let's close this ticket.

We can re-open if it's still needed.
