### ISSUE TITLE
jobs get stuck on LSF due to `type==X86_64` requirements

### ISSUE THREAD

**Issue by stevekm** [mskcc/ridgeback#37]
Ridgeback jobs submitted to LSF are getting stuck in pending state because they have `type==X86_64` as a resource requirement. Need to figure out where this requirement is coming from and how to remove it, if possible.

**Comment by allanbolipata** [comment]
Oh rough, which `toil` are you using? We remove this in the MSKCC fork.

We actually need to make a PR to the DataBiosphere main repo that removes this string.

**Comment by allanbolipata** [comment]
It looks like it's been removed in version `3.21.0` of `toil`; if you're using `3.19.0` from the main DataBiosphere repo, though, it's still in there: https://github.com/DataBiosphere/toil/blob/releases/3.19.0/src/toil/batchSystems/lsf.py#L170
